name: Test Contracts test

on:
  push:

jobs:
  test-contracts:
    runs-on: ubuntu-latest
    container: node:20.12.2

    env:
      FORCE_COLOR: true
      PRIVATE_KEY: 'bbbbbbbbbbbbbbbbbbbbbbbbbbbbbaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v4
        id: yarn-cache # use this to check for `cache-hit` (`steps.yarn-cache.outputs.cache-hit != 'true'`)
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Debug cache
        run: |
          echo "Cache hit: ${{ steps.yarn-cache.outputs.cache-hit }}"
          echo "Yarn cache location:"
          yarn cache dir
          echo "Yarn cache size:"
          du -sh $(yarn cache dir)
          echo "Timing before yarn install"
          date +%s

      - run: yarn install

      - name: Debug after install
        run: |
          echo "Timing after yarn install"
          date +%s
          echo "Final cache size:"
          du -sh $(yarn cache dir)
      - run: node_modules/.bin/solhint contracts/**/*.sol
      - run: node_modules/.bin/hardhat compile
      - run: node_modules/.bin/hardhat test
